import type { Metadata } from "next";
import "./globals.css";
import {Poppins} from 'next/font/google';

const mainFontFamily = Poppins({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-family-main',
});

export const metadata: Metadata = {
  title: "Empregue",
  description: "Generated by Equipe 05",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={mainFontFamily.variable}>
      <head>
      
      </head>
      <body>{children}</body>
    </html>
  );
}
